root = "."
tmp_dir = "tmp"

[build]
  cmd = "go build -o ./tmp/server ./cmd/server/"
  bin = "./tmp/server"
  delay = 1000
  exclude_dir = ["tmp", "vendor"]
  include_ext = ["go", "tpl", "tmpl", "html"]
  exclude_regex = ["_test.go"]

[watch]
  poll = true
  poll_interval = 500

[log]
  main_only = true

[misc]
  clean_on_exit = true
